services:
  m1:
    # Q learning worm
    build:
      context: .
      dockerfile: Dockerfile
      target: image-infected-learn
    ports:
      - 5050:80
    networks:
      netw:
        ipv4_address: 10.0.0.11
    environment:
      - IP_ADDR="10.0.0.11"
  m1-r:
    # Prod Q learning worm
    build:
      context: .
      dockerfile: Dockerfile
      target: image-infected-run
    ports:
      - 5050:80
    networks:
      netw:
        ipv4_address: 10.0.0.11
    environment:
      - IP_ADDR="10.0.0.11"
  m1-r-02:
    # Prod Q learning worm with randomized IoT device
    build:
      context: .
      dockerfile: Dockerfile
      target: image-infected-run
    ports:
      - 5050:80
    networks:
      netw:
        ipv4_address: 10.0.0.11
    environment:
      - IP_ADDR="10.0.0.11"
  m3:
    # Static worm
    build:
      context: .
      dockerfile: Dockerfile
      target: image-infected-static
    ports:
      - 5050:80
    networks:
      netw:
        ipv4_address: 10.0.0.11
    environment:
      - IP_ADDR="10.0.0.11"
  m4:
    # Deep Q learning worm
    # using tensorflow
    build:
        context: .
        dockerfile: dql.Dockerfile
    privileged: true
    ports:
      - 5050:80
    networks:
      netw:
        ipv4_address: 10.0.0.11
    environment:
      - IP_ADDR="10.0.0.11"
  m2:
    # Clean machine without worm
    build:
      context: .
      dockerfile: Dockerfile
      target: image-clean
    privileged: true
    ports:
      - 5051:81
    networks:
      netw:
        ipv4_address: 10.0.0.12
  honeypot:
    # Honeypot with several ports and IP addresses open
    build:
      context: .
      dockerfile: honeypot.Dockerfile
    privileged: true
    ports:
      - 5052:81
    networks:
      netw:
        priority: 1000
        ipv4_address: 10.0.0.15
      net1:
        priority: 900
      net2:
        priority: 800
      net3:
        priority: 700
networks:
  netw:
    ipam:
     config:
       - subnet: 10.0.0.0/24
         gateway: 10.0.0.1
  net1:
  net2:
  net3: